name: Docker CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        args: --exit-code 1 --file Dockerfile
        trivy-config: trivy.yaml
